---
- name: configurar servidor de app java
  hosts: app01

  user: vagrant
  become: yes

  var:
    - dbhost: "db01"
    - dbname: "notes"
    - dbusername: "notesapps"
    - dbpassword:  "devops"
  tasks:
    - name: config host do lab ansible
      ineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01
    - name: add user de app
      user: app
      comment: usuer de aplicacao
      uuid: 500
    - name: instalar mavem
      apt:
        name: mavem
        state: latest
    - name: instalar java
      apt:
        name: openjdk-11-jdk
        state: latest
    - name: criacao de dir de app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: clone do repositorio notes - app
      git:
        repo: "https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git"
        dest: /opt/notes
        clone: yes
        force: yes
    - name: Configurar arquivo de propriedades para camada de banco de dados
      templates:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: gerar pacotes da aplicacao
        command: mvm -f /opt/notes.pom.xml package
        become_user: app
        