Vagrant.configure("2") do |config|

  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.synced_folder ".", "/vagrant"
end